### ISSUE TITLE
get error of compatible

### ISSUE THREAD

**Issue by purvi123** [ibnab/magento2-delete-orders#1]
hi,
Fatal error: Declaration of Ibnab\DeleteOrders\Controller\Adminhtml\Order\MassDelete::massAction() must be compatible with Magento\Sales\Controller\Adminhtml\Order\AbstractMassAction::massAction(Magento\Framework\Model\Resource\Db\Collection\AbstractCollection $collection)

**Comment by ibnab** [comment]
it's work perfectly in release 2.0 what's your version of magento2

**Comment by purvi123** [comment]
Hello,

Thanks for your reply.
My version is "1.0.0-beta". Is it work on this version?

_Regards,_**

_Purvi Vora_

*
*

**Comment by ibnab** [comment]
no you need upgrade to release 2.0 because many issue is change in the code .

**Comment by ibnab** [comment]
please close the issue
