### ISSUE TITLE
It will orverride Magento Default Options.

### ISSUE THREAD

**Issue by shahankitb997** [ibnab/magento2-delete-orders#11]
I'm using Magento 2 CE Version 2.1.1

It removes all Sales Options & Instead of that only put "Delete" it should be All + Delete
![1](https://cloud.githubusercontent.com/assets/20528998/19305203/7862533e-90a2-11e6-939f-bac7e01b428f.png)

**Comment by ibnab** [comment]
it's not updated yet plz use version 
http://store.ibnab.com/magento-2-extensions/magento2-delete-orders.html

**Comment by shahankitb997** [comment]
Thanks. It Solved :)
