### ISSUE TITLE
Other order batch options missing (Magento 2.1.4)

### ISSUE THREAD

**Issue by srokatonie** [ibnab/magento2-delete-orders#13]
After installing module you have only "Delete" option. With module:
![screen shot 2017-03-10 at 12 29 56](https://cloud.githubusercontent.com/assets/12460055/23793831/7d87fa98-058d-11e7-8f9b-8517e7c354a6.png)

Without (default view):
![screen shot 2017-03-10 at 12 30 54](https://cloud.githubusercontent.com/assets/12460055/23793841/89470612-058d-11e7-8962-bb8c04196e24.png)

**Comment by srokatonie** [comment]
I noticed someone raised similar issue. Sorry!

**Comment by ibnab** [comment]
download from our official website plz
