### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by trichter01** [ibnab/magento2-delete-orders#4]
n

**Comment by ibnab** [comment]
you need verify if you have this file etc/adminhtml/routes.xml

**Comment by trichter01** [comment]
I have the file

**Comment by ibnab** [comment]
what's mag2 version you using

**Comment by trichter01** [comment]
Im using 2.0.4

**Comment by ibnab** [comment]
iwill try now  and i will response you

**Comment by trichter01** [comment]
Thank you

**Comment by ibnab** [comment]
i test and it work for me correctly i think it's just problem of permission , or not exist files

**Comment by trichter01** [comment]
I'm still seeing the 404 error similarly to Paul E who posted screenshots on your site(http://www.ibnab.com/en/blog/magento-2/magento-2-extension-our-new-extension-delete-orders). 
Was there a fix for him?
