### ISSUE TITLE
remove extension

### ISSUE THREAD

**Issue by trichter01** [ibnab/magento2-delete-orders#5]
no

**Comment by ibnab** [comment]
it's work perfectly in magento 2.04 we just try yesterday ....
about remove it's simple just search in the net how remove extension in mag2 you can find the solution

**Comment by trichter01** [comment]
Excellent thanks. If this is helpful to anyone, disabling the extension from shell:
php bin/magento module:disable Ibnab_DeleteOrders

I found this extension to be much more useful:
Wyomind > OrderEraser (https://www.wyomind.com/order-eraser-magento.html)

**Comment by ibnab** [comment]
i see you play from first here is not for advise i will upload video of how i nstall in clean mag2 installation
this ,is dirty way ...
