### ISSUE TITLE
404 on delete orders

### ISSUE THREAD

**Issue by mombrea** [ibnab/magento2-delete-orders#9]
I've installed the extension as instructed and have the option to delete an order, however the delete always results in a 404 page and the order is not removed. I'm using Magento CE 2.0.6

**Comment by ibnab** [comment]
plz see this video i have the steps of installation:
https://www.youtube.com/watch?feature=player_embedded&v=HrzERj9e0z4

**Comment by digitalredefined** [comment]
Followed the instructions on the video and still 404. 2.0.10

**Comment by ibnab** [comment]
@digitalredefned download the last version from http://store.ibnab.com/magento-2-extensions/magento2-delete-orders.html
